project : "methylGPT"

pretrained_file : "methylGPT/dev_pretraining_test-dataset_CpGs_type3-preprocessing_False-Nov29-12-01/best_model_epoch6.pt"
weights_save_path : "methylGPT/finetuning/age_prediction/age_finetune_ckpt"

train_file : "/Entropy/Projects/multimodal/kying/A.Y/project/methylGPT/finetuning/age_prediction/age_data/altumage_metadata/train_data_altumage_8049_age_from_processed_type3_parquet_shuffled_predicted_age_6827_train_split_5461.parquet"
valid_file : "/Entropy/Projects/multimodal/kying/A.Y/project/methylGPT/finetuning/age_prediction/age_data/altumage_metadata/train_data_altumage_8049_age_from_processed_type3_parquet_shuffled_predicted_age_6827_valid_split_1366.parquet"
test_file : "/Entropy/Projects/multimodal/kying/A.Y/project/methylGPT/finetuning/age_prediction/age_data/altumage_metadata/test_data_altumage_5455_age_from_processed_type3_parquet_shuffled_predicted_age_4626.parquet"

cpg_sites: 49156
mask_ratio: 0
mlm_wt: 0
weight_decay : 0
gradient_clip_val : 1.0
log_every_n_steps : 1
pretrained_lr : 1e-4
head_lr : 1e-3
train_batch_size : 16
valid_batch_size : 16
max_epochs : 300
gpus : 2

mode: "train"
valid_ckpt_path: "None"
wandb: True


